[*] Running ...
[*] Dataset loaded: D:\ProgramLanguages\Programs\Python\code-gen\reevo/problems/tsp_gls\dataset/train200_dataset.npy with 10 instances.
D:\ProgramLanguages\Programs\Python\code-gen\reevo\problems\tsp_gls\gpt.py:22: RuntimeWarning: invalid value encountered in divide
  edge_usage = (edge_usage - np.min(edge_usage)) / (np.max(edge_usage) - np.min(edge_usage))
Traceback (most recent call last):
  File "D:\ProgramLanguages\Programs\Python\code-gen\reevo/problems/tsp_gls/eval.py", line 51, in <module>
    obj = solve(instance)
          ^^^^^^^^^^^^^^^
  File "D:\ProgramLanguages\Programs\Python\code-gen\reevo/problems/tsp_gls/eval.py", line 21, in solve
    heu = heuristics(inst.distmat.copy())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramLanguages\Programs\Python\code-gen\reevo\problems\tsp_gls\gpt.py", line 37, in heuristics_v2
    
TypeError: maximum() got an unexpected keyword argument 'axis'
