[*] Running ...
[*] Dataset loaded: E:\Projects\CO\reevo-main_1/problems/tsp_gls\dataset/train200_dataset.npy with 10 instances.
Traceback (most recent call last):
  File "E:\Projects\CO\reevo-main_1/problems/tsp_gls/eval.py", line 51, in <module>
    obj = solve(instance)
          ^^^^^^^^^^^^^^^
  File "E:\Projects\CO\reevo-main_1/problems/tsp_gls/eval.py", line 21, in solve
    heu = heuristics(inst.distmat.copy())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\CO\reevo-main_1\problems\tsp_gls\gpt.py", line 40, in heuristics_v2
    for i, j in mst_edges:
           ^^^^^^^^^^^^^^^
  File "E:\Projects\CO\reevo-main_1\problems\tsp_gls\gpt.py", line 21, in find_set
    for i in range(num_vertices):
       ^^^^^^^^^^^^
TypeError: only integer scalar arrays can be converted to a scalar index
