[*] Running ...
[*] Dataset loaded: E:\Projects\CO\reevo-main/problems/tsp_gls\dataset/train200_dataset.npy with 10 instances.
Traceback (most recent call last):
  File "E:\Projects\CO\reevo-main/problems/tsp_gls/eval.py", line 49, in <module>
    obj = solve(instance)
          ^^^^^^^^^^^^^^^
  File "E:\Projects\CO\reevo-main/problems/tsp_gls/eval.py", line 19, in solve
    heu = heuristics(inst.distmat.copy())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\CO\reevo-main\problems\tsp_gls\gpt.py", line 23, in heuristics_v2
    
NameError: name 'random' is not defined
